static content creation for all the 114 species from wiki
EnsemblGenomes/ensembl-static pull request #145
Opened 2024-11-18 11:50 UTC by Dishalodha

2025-01-03 17:46 UTC, JAlvarezJarreta requested changes

2025-01-03 17:46 UTC, JAlvarezJarreta commented on plants/species/Hordeum_vulgare/Hordeum_vulgare_hid055_annotation.md
> +Genomic annotation was deposited along with initial assembly submission by ["Martin Luther University Halle-Wittenberg"](URL_GOES_HERE).
```suggestion
Genomic annotation was deposited along with initial assembly submission by ["Martin Luther University Halle-Wittenberg"](https://www.uni-halle.de/?lang=en).
```

2025-01-03 17:46 UTC, JAlvarezJarreta commented on plants/species/Hordeum_vulgare/Hordeum_vulgare_hid055_about.md
> +winter-hardy than wheat or rye.
This is the only `about.md` file with more description than the rest. Is it expected?

2025-01-03 17:46 UTC, JAlvarezJarreta commented on plants/species/Hordeum_vulgare/Hordeum_vulgare_hid101_annotation.md
> +Genomic annotation was deposited along with initial assembly submission by ["Martin Luther University Halle-Wittenberg"](URL_GOES_HERE).
```suggestion
Genomic annotation was deposited along with initial assembly submission by ["Martin Luther University Halle-Wittenberg"](https://www.uni-halle.de/?lang=en).
```

2025-01-03 17:46 UTC, JAlvarezJarreta commented on plants/species/Hordeum_vulgare/Hordeum_vulgare_hid249_annotation.md
> +Genomic annotation was deposited along with initial assembly submission by ["Martin Luther University Halle-Wittenberg"](URL_GOES_HERE).
```suggestion
Genomic annotation was deposited along with initial assembly submission by ["Martin Luther University Halle-Wittenberg"](https://www.uni-halle.de/?lang=en).
```

2025-01-03 17:46 UTC, JAlvarezJarreta commented on plants/species/Hordeum_vulgare/Hordeum_vulgare_hid357_annotation.md
> +Genomic annotation was deposited along with initial assembly submission by ["Martin Luther University Halle-Wittenberg"](URL_GOES_HERE).
```suggestion
Genomic annotation was deposited along with initial assembly submission by ["Martin Luther University Halle-Wittenberg"](https://www.uni-halle.de/?lang=en).
```

2025-01-03 17:46 UTC, JAlvarezJarreta commented on plants/species/Hordeum_vulgare/Hordeum_vulgare_hid380_annotation.md
> +Genomic annotation was deposited along with initial assembly submission by ["Martin Luther University Halle-Wittenberg"](URL_GOES_HERE).
```suggestion
Genomic annotation was deposited along with initial assembly submission by ["Martin Luther University Halle-Wittenberg"](https://www.uni-halle.de/?lang=en).
```

2025-01-03 17:46 UTC, JAlvarezJarreta commented on plants/species/Vitis/Vitis_vinifera/Vitis_vinifera_annotation.md
> +ensembl-plants displaying genes imported from [NCBI RefSeq](https://www.ncbi.nlm.nih.gov/genome/annotation_euk/Vitis_vinifera/GCF_030704535.1-RS_2023_09.html) annotation release vGCF_030704535.1-RS_2
```suggestion
ensembl-plants displaying genes imported from [NCBI RefSeq](https://www.ncbi.nlm.nih.gov/genome/annotation_euk/Vitis_vinifera/GCF_030704535.1-RS_2023_09.html) annotation release GCF_030704535.1-RS_2023_09.

```

2025-01-03 17:46 UTC, JAlvarezJarreta commented on plants/species/Vitis/Vitis_vinifera/Vitis_vinifera_assembly.md
> +The assembly presented here has been imported from [INSDC](http://www.insdc.org) and is linked to the assembly accession [[GCA\_030704535.1](http://www.ebi.ac.uk/ena/data/view/GCA_030704535.1)].
```suggestion
The assembly presented here has been imported from [INSDC](http://www.insdc.org) and is linked to the assembly accession [[GCA\_030704535.1](https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_030704535.1/)].
```

2025-01-03 17:46 UTC, JAlvarezJarreta commented on plants/species/Sphenostylis/Sphenostylis_stenocarpa/Sphenostylis_stenocarpa_annotation.md
> +Genomic annotation was deposited along with initial assembly submission by ["International Livestock Research Institute"](URL_GOES_HERE).
```suggestion
Genomic annotation was deposited along with initial assembly submission by ["International Livestock Research Institute"](https://www.ilri.org).
```

2025-01-03 17:46 UTC, JAlvarezJarreta commented on plants/species/Sphenostylis/Sphenostylis_stenocarpa/Sphenostylis_stenocarpa_about.md
> +
```suggestion
Picture credit: [LICENSE TYPE]() via Wikimedia Commons [(Image source)]()
```
Has someone contacted the provider already to get an image?

2025-01-13 08:11 UTC, Dishalodha commented on plants/species/Sphenostylis/Sphenostylis_stenocarpa/Sphenostylis_stenocarpa_about.md
> +
We didnt find an image in wiki and as per I understood its okay to not have an image but I will remove this and we can update it when we get an image

2025-01-14 13:59 UTC, imransl commented
@Dishalodha Can we merge this PR or does it need to be reviewed again?

2025-01-14 23:46 UTC, JAlvarezJarreta approved these changes
Couple of things to double-check to make sure we do not remove the rightful credits, but looks good otherwise. Thank you for making the changes!

2025-01-14 23:46 UTC, JAlvarezJarreta commented on plants/species/Sphenostylis/Sphenostylis_stenocarpa/Sphenostylis_stenocarpa_about.md
> -(Text from [Wikipedia](https://en.wikipedia.org/).)
Just double-checking this has not been removing by mistake.

2025-01-14 23:46 UTC, JAlvarezJarreta commented on plants/species/Vitis/Vitis_vinifera/Vitis_vinifera_about.md
> -(Text from [Wikipedia](https://en.wikipedia.org/).)
Same as before.

2025-01-14 23:54 UTC, JAlvarezJarreta commented
> @Dishalodha Can we merge this PR or does it need to be reviewed again?

Hi @imransl , Disha is on leave this week. If you need this merged this week, I believe it is in a good status to do so and Disha can make any additional PRs next week when she is back if there is something that needs to be corrected.

2025-01-23 14:01 UTC, JAlvarezJarreta approved these changes
Look good to me now 👍

2025-01-27 11:49 UTC, merged