Static content completed for all six bemisia tabaci e103.
EnsemblGenomes/ensembl-static pull request #39
Opened 2020-12-17 15:08 UTC by ens-LCampbell

Ensembl metazoa 103 is the first initial release for the Bemisia tabaci sp. (all belong to cryptic species complex). Species image files contain the same exact image with specific GCA assembly accession appended to each.

2020-12-17 15:35 UTC, azangru commented on metazoa/species/Bemisia/Bemisia_tabaci/Bemisia_tabaci_gca903994095_assembly.md
> +A field-collected colony (Namulonge, Uganda) was established, maintained and inbred \(F6 generation\) by [Dr Habibu Mugerwa](https://scholar.google.com/citations?user=srDeBUgAAAAJ&hl=en) at the quara
Could you please delete the backslashes before the parentheses (`\(F6 generation\)`)?

2020-12-17 15:37 UTC, azangru commented on metazoa/species/Bemisia/Bemisia_tabaci/Bemisia_tabaci_gca903994095_assembly.md
> +A field-collected colony (Namulonge, Uganda) was established, maintained and inbred \(F6 generation\) by [Dr Habibu Mugerwa](https://scholar.google.com/citations?user=srDeBUgAAAAJ&hl=en) at the quara
`\(F6 generation\)` -> `(F6 generation)`

2020-12-17 15:38 UTC, azangru commented on metazoa/species/Bemisia/Bemisia_tabaci/Bemisia_tabaci_gca903994105_assembly.md
> +A field-collected colony (Salem, Tamil Nadu, India) was established, maintained and inbred \(F5 generation\) by [Prof Maruthi Gowda](https://scholar.google.com.au/citations?user=5czCi6oAAAAJ&hl=en) a
`\(F5 generation\)` -> `(F5 generation)`

2020-12-17 16:22 UTC, ens-ap5 requested changes
Backslashes to be removed as per Andrey's comments

2020-12-18 09:44 UTC, ens-LCampbell commented
My apologies, brackets are removed. I was working with content md files passed from collaborators and I missed those brackets.

2020-12-18 15:26 UTC, merged